![header.png](https://lh4.googleusercontent.com/FWBHWkTBQHZQrtGwvdPeHwpTNJ2PQiQYa7zfSxQwhHH92n34SU9dkcbvp0BbBmtK1djie1C1_f8Y9t8XbDHYXxlO5PKQZO2JdB_Xfe_4wD9GIEcUW6KSoE8YzVioVVOPQQ=w5014)

Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

Make sure you fill in any place that says `YOUR CODE HERE` or "YOUR ANSWER HERE", as well as your name and collaborators below:

In [ ]:
NAME = ""
COLLABORATORS = ""

---

# Challenge 5A: Solving $A\vec{x} = \vec{b}$

> _It is impossible to dissociate language from science or science from language, because every natural science always involves three things: the sequence of phenomena on which the science is based; the abstract concepts which call these phenomena to mind; and the words in which the concepts are expressed. To call forth a concept, a word is needed; to portray a phenomenon, a concept is needed. All three mirror one and the same reality._
>
> — Antoine Lavoisier (1789)

In this challenge and its other part, you will learn what matrices really _are_ in the course of trying to understand two primary objects of study in linear algebra, namely the following matrix equations:

1. $A\vec{x} = \vec{b}$, used to solve systems of equations
2. $A\vec{x} = \lambda \vec{x}$, used to understand how matrices _transform_ spaces

(Here, $\vec{b}$ is some arbitrary vector and $\lambda$ is a scalar.)

By the end of this challenge, you should:

- [ ] possess the language to talk about _linear transformations_, and how they enable you to morph and mold (vector) spaces as you see fit
- [ ] be able to solve systems of equations, and furthermore know exactly when you can and cannot do so

Let's jump right into it.

## Problem 1: Write each of the following systems of equations as a single matrix:

a.
$
\begin{cases}
3y - z &= 0 \\
-2x + y + 2z &= 0 \\
x - 5z &= 0
\end{cases}
$

b.
$
\begin{cases}
2x_1 + 3x_2 - x_3 &= 1 \\
-2x_2 + x_3 &= 2 \\
x_1 - 2x_3 &= -1
\end{cases}
$

Let

$$
\tilde{A} =
\begin{bmatrix}
0 & 3 & -1\\
-2 & 1 & 2\\
1 & 0 & -5\\
\end{bmatrix}
$$

represent the set of cofficients and

$$
\vec{x}
=
\begin{bmatrix}
x\\
y\\
z
\end{bmatrix}
$$

represent the solution vector

and

$$
\vec{b}
=
\begin{bmatrix}
0\\
0\\
0
\end{bmatrix}
$$

represent the right-hand side of the equation. Then the system of linear equations can be expressed via

$$
\tilde{A}\vec{x} = \vec{b}
\iff
\begin{bmatrix}
0 & 3 & -1\\
-2 & 1 & 2\\
1 & 0 & -5\\
\end{bmatrix}
\begin{bmatrix}
x\\
y\\
z
\end{bmatrix}
=
\begin{bmatrix}
0\\
0\\
0
\end{bmatrix}
$$

Same goes for letter $b$ with


$$
\tilde{A} =
\begin{bmatrix}
2 & 3 & -1\\
0 & -2 & 2\\
1 & 0 & -2\\
\end{bmatrix}
$$
,
$$
\vec{x}
=
\begin{bmatrix}
x\\
y\\
z
\end{bmatrix}
$$
,

and

$$
\vec{b}
=
\begin{bmatrix}
1\\
2\\
-1
\end{bmatrix}
$$


with equation of form

$$
\tilde{A} \vec{x} = \vec{b}
\iff
\begin{bmatrix}
2 & 3 & -1\\
0 & -2 & 2\\
1 & 0 & -2\\
\end{bmatrix}
\begin{bmatrix}
x\\
y\\
z
\end{bmatrix}
=
\begin{bmatrix}
1\\
2\\
-1
\end{bmatrix}
$$


To solve the system of equations for both items, a simple matrix inversion and matrix multiplication should do the trick.


a.

In [6]:
import numpy as np

# performing matrix inversion and multiplication

# item a

A = np.array([[0, 3, -1],
              [-2, 1, 2],
              [1, 0, -5]])

A_inv = np.linalg.inv(A)

print("Original Matrix:")
print(A)
print("\nInverse Matrix:")
print(A_inv)

print("Performing matrix multiplication")
vector = np.array([0, 0, 0])

result = np.dot(A_inv, vector)
print(result)

# item b
A = np.array([[2, 3, -1],
              [0, -2, 1],
              [1, 0, -2]])

A_inv = np.linalg.inv(A)

print("Original Matrix:")
print(A)
print("\nInverse Matrix:")
print(A_inv)

print("Performing matrix multiplication")
vector = np.array([1, 2, -1])

result = np.dot(A_inv, vector)
print(result)

Original Matrix:
[[ 0  3 -1]
 [-2  1  2]
 [ 1  0 -5]]

Inverse Matrix:
[[ 0.2173913  -0.65217391 -0.30434783]
 [ 0.34782609 -0.04347826 -0.08695652]
 [ 0.04347826 -0.13043478 -0.26086957]]
Performing matrix multiplication
[0. 0. 0.]
Original Matrix:
[[ 2  3 -1]
 [ 0 -2  1]
 [ 1  0 -2]]

Inverse Matrix:
[[ 0.44444444  0.66666667  0.11111111]
 [ 0.11111111 -0.33333333 -0.22222222]
 [ 0.22222222  0.33333333 -0.44444444]]
Performing matrix multiplication
[ 1.66666667 -0.33333333  1.33333333]


## Definition: (linear transformation)

A **linear transformation** $T: \mathbb{R}^n \to \mathbb{R}^m$ is a mapping such that, for scalars $a$ and all $\vec{v}$, $\vec{w}$ $\in$ $\mathbb{R}^n$:

$$
T(\vec{v} + \vec{w}) = T(\vec{v}) + T(\vec{w})
$$

and

$$
T(a\vec{v}) = aT(\vec{v})
$$

**Q**: What happens to the zero vector $\vec{0}$ when you apply a linear transformation to it?

<details>
<summary>Answer</summary>
Choose $a = 0$ so that $T(0 \vec{v}) = T(\vec{0}) = (0)T(\vec{v}) = \vec{0}$. In other words, linear transformations always map the zero vector to itself.

Alternatively, all linear transformations preserve the _origin_.
</details>

## Proposition I: Matrices are linear transformations

1. Any $m \times n$ matrix defines a linear transformation $T: \mathbb{R}^n \to \mathbb{R}^m$ by matrix multiplication:

$$
T(\vec{v}) = A\vec{v}
$$

2. Every linear transformation $T: \mathbb{R}^n \to \mathbb{R}^m$ is given by the $m \times n$ matrix $[T]$:

$$
T(\vec{v}) = [T]\vec{v}
$$

where the ith column of $[T]$ is $T(\vec{e_i})$

## Problem 2: Prove Proposition I.

## Example: Identity transformation

The identity transformation $\text{id}: \mathbb{R}^n \to \mathbb{R}^n$ is linear and is given by the $n \times n$ identity matrix.

Applying it to any vector leaves it unchanged.

## Example: Scaling transformation

The transformation $T$ having the form $\begin{bmatrix} a & 0  \\ 0 & a \end{bmatrix}$ scales any vector in $\mathbb{R}^2$ by $a$, since $T\vec{e_1} = \begin{bmatrix} a  \\ 0 \end{bmatrix}$ and $T\vec{e_2} = \begin{bmatrix} 0  \\ a \end{bmatrix}$

## Example: Rotation transformation

The transformation $R$ that rotates a vector by $\theta$ counterclockwise around the origin is linear, and is given by:

$$
[R] = [R(\vec{e_1}), R(\vec{e_2})] = \begin{bmatrix} \cos{\theta} & -\sin{\theta} \\ \sin{\theta} & \cos{\theta} \end{bmatrix}
$$

where we denote the individual columns of $[R]$ by $R(\vec{e_1})$ and $R(\vec{e_2})$.

## Proposition II: Composition corresponds to matrix multiplication

If $S: \mathbb{R}^n \to \mathbb{R}^m$ and $T: \mathbb{R}^m \to \mathbb{R}^l$ are linear transformations represented by matrices $[S]$ and $[T]$ respectively, then the function composition $T \circ S$ is linear and $$[T \circ S] = [T][S]$$

---

Does this make sense? For example, if you want to apply the scaling and rotation transformations to a vector, you can just multiply said vector their representative matrices. The magic is that this works for _any_ linear transformation that can be represented by a matrix.

## Definition: (affine transformation)

A map $\vec{f}: \mathbb{R}^n \to \mathbb{R}^m$ is **affine** if the function $\vec{x} \mapsto \vec{f(\vec{x})} - \vec{f(\vec{0})}$ is linear.

---

In other words, an affine transformation is what you get if you do a linear transformation _and then_ move the $\vec{0}$ somewhere else. The reason why we're even bothering with this is because the layers of a neural network are generally _not_ linear but a combination of an affine transformation and a nonlinear activation function that determines what the neuron should output given the magnitude of its inputs. You have already seen one such activation function in Challenge 04: the sigmoid, and we will see more later.

For now, we study linear transformations because they are, in some sense, stuff we can completely understand. And because of this, all the theory of more complicated transformations are usually formulated on top of them.

**Q**: Is the map $\begin{pmatrix} x \\ y \end{pmatrix} \mapsto \begin{pmatrix} x - y + 2 \\ 2x + y + 1 \end{pmatrix}$ linear or affine?

<details>
<summary>Answer</summary>
It's affine, since it maps the zero vector $\begin{pmatrix} 0 \\ 0 \end{pmatrix} \mapsto \begin{pmatrix} 2 \\ 1 \end{pmatrix}$ and not to itself.
</details>

## Definition: (dot product)

The **dot product** of two vectors $\vec{x}, \vec{y} \in \mathbb{R}^n$ is given by:

$$
\vec{x} \cdot \vec{y} = \begin{bmatrix} x_1 \\ \vdots \\ x_n \end{bmatrix} \cdot \begin{bmatrix} y_1 \\ \vdots \\ y_n \end{bmatrix} = \sum{x_i y_i}
$$

---

Note that we can also write this as $\vec{x} \cdot \vec{y} = \vec{x}^T \, \vec{y} = \vec{y}^T \, \vec{x}$.

Also, the dot product produces a _scalar_.


## Definition: (length of a vector)

The **length of a vector** $\vec{v}$ is

$$
|\vec{v}| = \sqrt{\vec{v} \cdot \vec{v}} = \sqrt{\sum{v_i^2}}
$$

A vector of length 1 is also called a **unit vector**, and you can always turn $\vec{v}$ into a unit vector in the same direction by dividing it by its length:

$$
\hat{v} = \frac{\vec{v}}{|\vec{v}|}
$$

## Definition: (angle between two vectors)

The angle $\alpha$ between two vectors $\vec{v}$ and $\vec{w}$ is given by:

$$
\vec{v} \cdot \vec{w} = |\vec{v}||\vec{w}| \cos{\alpha}
$$

---

When $\alpha = \pi / 2 = 90\degree$, $\vec{v} \cdot \vec{w} = 0$. In this case, we say that the vectors are **orthogonal** to each other.

## Problem (bonus): Prove the following trigonometric identities using the rotation transformation.

a. $\cos{\alpha + \beta} = \cos{\alpha}\cos{\beta} - \sin{\alpha}\sin{\beta}$

b. $\sin{\alpha + \beta} = \sin{\alpha}\cos{\beta} + \cos{\alpha}\sin{\beta}$

## Definition: (length of a matrix)

The **length of a matrix** $A$ is simply the square root of the sum of each of its entries squared, or:

$$
|A|^2 = \sum{a}^2_{ij}
$$

---

We call this a _length_ because it allows us to talk about how 'close' linear transformations are to each other. Unfurl an $m \times n$ matrix as a point in $\mathbb{R}^{mn}$ (i.e. a point with $mn$ entries), and by comparing its length with other matrices of the same shape we are able to precisely tell if its corresponding transformation does nearly the same thing as another.

(Don't think too hard about this point if it didn't make sense to you. It's just a neat addition to one's mathematical intuition.)

## Example: Length of a matrix

If $A = \begin{bmatrix} 1 & 2 \\ 0 & 1 \end{bmatrix}$, then $|A| = \sqrt{1^2 + 2^2 + 0^2 + 1^2} = \sqrt{6}$

---

## Example: Representing systems of equations as matrices

Consider the following system of equations:


$$
\begin{cases}
2x + y + 3z &= 1 \\
x - y \, &= 1 \\
2x \, + z &= 1
\end{cases}
$$

We can write this as a matrix equation if we define the **coefficient matrix**

$$
A = \begin{bmatrix} 2 & 1 & 3 \\ 1 & -1 & 0 \\ 2 & 0 & 1 \end{bmatrix}
$$

the vector of unknowns $\vec{x} = \begin{bmatrix} x \\ y \\ z \end{bmatrix}$ and the constants $\vec{b} = \begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}$, so that we can write:

$$
\begin{bmatrix} 2 & 1 & 3 \\ 1 & -1 & 0 \\ 2 & 0 & 1 \end{bmatrix}
\begin{bmatrix} x \\ y \\ z \end{bmatrix}
=
\begin{bmatrix} 1 \\ 1 \\ 1 \end{bmatrix}
$$

or

$$A \vec{x} = \vec{b}$$

We can even write this more compactly as the **augmented matrix** $[A | \vec{b}]$:

$$
\begin{bmatrix}
2 & 1 & 3 & \bigm| & 1 \\
1 & -1 & 0 & \bigm| & 1 \\
2 & 0 & 1 & \bigm| & 1
\end{bmatrix}
$$

## Definition: (row operations)

A **row operation** on a matrix is one of the following:

1. Multiplying a row by a nonzero number
2. Adding a multiple of a row to another row
3. Exchanging two rows

## Example: solving a matrix using row operations

We can solve the system of equations associated with the augmented matrix $A = \begin{bmatrix} 2 & 1 & 3 & \bigm| & 1 \\ 1 & -1 & 0 & \bigm| & 1 \\ 2 & 0 & 1 & \bigm| & 1\end{bmatrix}$ as follows:

1. Divide row 1 by 2, add -1/2 row 1 to row 2, then subtract row 1 from row 3:
$$
\begin{bmatrix}
1 & 1/2 & 3/2 & \bigm| & 1/2 \\
0 & -3/2 & -3/2 & \bigm| & 1/2 \\
0 & -1 & -2 & \bigm| & 0
\end{bmatrix}
$$

3. Multiply row 2 by -2/3, then add result to row 3:
$$
\begin{bmatrix}
1 & 1/2 & 3/2 & \bigm| & 1/2 \\
0 & 1 & 1 & \bigm| & -1/3 \\
0 & 0 & -1 & \bigm| & -1/3
\end{bmatrix}
$$

5. Subtract 1/2 row 2 from row 1:
$$
\begin{bmatrix}
1 & 0 & 1 & \bigm| & 2/3 \\
0 & 1 & 1 & \bigm| & -1/3 \\
0 & 0 & 1 & \bigm| & 1/3
\end{bmatrix}
$$

7. Subtract row 3 from row 1:
$$
\begin{bmatrix}
1 & 0 & 0 & \bigm| & 1/3 \\
0 & 1 & 1 & \bigm| & -1/3 \\
0 & 0 & 1 & \bigm| & 1/3
\end{bmatrix}
$$

9. Subtract row 3 from row 2:
$$
\begin{bmatrix}
1 & 0 & 0 & \bigm| & 1/3 \\
0 & 1 & 0 & \bigm| & -2/3 \\
0 & 0 & 1 & \bigm| & 1/3
\end{bmatrix}
$$

from which we can immediately read off the solutions:


$$
\begin{bmatrix}
x & 0 & 0 & \bigm| & 1/3 \\
0 & y & 0 & \bigm| & -2/3 \\
0 & 0 & z & \bigm| & 1/3
\end{bmatrix}
$$

or $x = 1/3$, $y = -2/3$, and $z = 1/3$

## Definition: (row echelon form)

A matrix is in **row echelon form** or **row-reduced form** if all of the following conditions are satisfied:

1. In every row, the first nonzero entry is 1, called the **pivotal 1**.
2. The pivotal 1 of a lower row is always to the right of the pivotal 1 of a higher row.
3. In every column that contains a pivotal 1, all other entries are 0.
4. Any rows consisting entirely of 0's are at the bottom.

We also say that a matrix is in **column echelon form** if its transpose is in row echelon form.

For an augmented matrix $[A|\vec{b}]$, we can also denote its row echelon form by $[\tilde{A}|\tilde{b}]$ and call $\tilde{A}$ a **row-reduced matrix** and $\tilde{b}$ a **row-reduced vector**.

---

It is possible to show that the row echelon form of a matrix is _unique_ regardless of which row operations you used to derive it.

## Example: Matrices in echelon form

All of these matrices are in echelon form, with the pivotal 1's underlined:

$$
\begin{bmatrix}
\underline{1} & 0 & 0 & 3 \\
0 & \underline{1} & 0 & -2 \\
0 & 0 & \underline{1} & 1
\end{bmatrix}
$$

$$
\begin{bmatrix}
\underline{1} & 1 & 0 & 0 \\
0 & 0 & \underline{1} & 0 \\
0 & 0 & 0 & \underline{1}
\end{bmatrix}
$$

$$
\begin{bmatrix}
0 & \underline{1} & 3 & 0 & 0 & 3 & 0 & -4 \\
0 & 0 & 0 & \underline{1} & -2 & 1 & 0 & 1 \\
0 & 0 & 0 & 0 & 0 & 0 & \underline{1} & 2
\end{bmatrix}
$$

**Q**: Which of these are in echelon form?

a. $
\begin{bmatrix}
1 & 0 & 0 & 2 \\
0 & 0 & 1 & -1 \\
0 & 1 & 0 & 1
\end{bmatrix}
$

b. $
\begin{bmatrix}
1 & 1 & 0 &  1 \\
0 & 0 & 2 &  0 \\
0 & 0 & 0 &  1
\end{bmatrix}
$

c. $
\begin{bmatrix}
0 & 0 & 0 \\
1 & 0 & 0 \\
0 & 1 & 0
\end{bmatrix}
$


## Definition: (elementary matrices)

1. The **type 1 elementary matrix** $E_1(i, x)$ is the square matrix whose nondiagonal terms are 0, and every entry on the diagonal except for the $(i, i)$th entry which is nonzero
2. The **type 2 elementary matrix** $E_2(i, j, x)$, i $\neq j$, is the square matrix whose diagonal entries are 1 and all entries 0 except for the $(i, j)$th which is x.
3. The **type 3 elementary matrix** $E_3(i, j), $$i \neq  j$, is the square matrix whose entries $i, j$ and $j, i$ are 1, and all other entries on the diagonal except $i,i$ and $j,j$, which are 0.

---

You should verify for yourself that multiplying a matrix $A$ on the left by:

1. $E_1(i, x)$ multiplies the ith row of $A$ by $x$.
2. $E_2(i, j, x)$ adds ($x$ times the jth row) to the ith row.
3. $E_3(i, j)$ exchanges the ith and jth rows of $A$

Or in other words, the elementary matrices are how you actually do row operations purely in the language of linear algebra.

## Examples: Elementary matrices

1. $E_1(3, 2) = \begin{bmatrix} 1 & 0 & 0 & 0 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 2 & 0 \\ 0 & 0 & 0 & 1 \end{bmatrix}$
   
2. $E_2(1, 3, -3) = \begin{bmatrix} 1 & 0 & -3 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}$

3. $E_3(2, 3) = \begin{bmatrix} 1 & 0 & 0 & 0 & 0 \\ 0 & 0 & 1 & 0 & 0 \\ 0 & 1 & 0 & 0 & 0 \\ 0 & 0 & 0 & 1 & 0 \\ 0 & 0 & 0 & 0 & 1 \end{bmatrix}$

**Q**: Let $$A = \begin{bmatrix} 1 & 0 \\ 0 & 2 \\ 2 & 1 \\ 1 & 1 \end{bmatrix}$$

What is $E_1(3,2)A$?

## Problem 3: Using elementary matrices, row reduce each matrix in Problem 2.

You may use `numpy` for this, but you need to show each operation.

## Proposition III: Solution to $A\vec{x} = \vec{b}$ via row reduction

If you have a system of equations represented by the augmented matrix $[A|\vec{b}]$, then for its row-reduced form $[\tilde{A}|\tilde{b}]$ and the matrix equation $A\vec{x} = \vec{b}$:

1. If the row-reduced vector $\tilde{b}$ contains a pivotal 1, then the system has _no_ solutions.
2. Otherwise:
    1. If each column of $\tilde{A}$ has a pivotal 1, the system has a _unique_ solution.
    2. If at least one column of $\tilde{A}$ is non-pivotal (i.e. doesn't have a pivotal 1), the system has _infinitely many_ solutions.

## Example: Telling at a glance how many solutions a system of equations has

1. Consider the system of equations:

$$
\begin{cases}
2x + y + 3z &= 1 \\
x - y &= 1 \\
x + y + 2z &= 1
\end{cases}
$$

then $[A|\vec{b}] = \begin{bmatrix} 2 & 1 & 3 & \bigm| & 1 \\ 1 & -1 & 0 & \bigm| & 1 \\ 1 & 1 & 2 & \bigm| & 1 \end{bmatrix}$

which row-reduces to $[\tilde{A}|\tilde{b}] = \begin{bmatrix} \underline{1} & 0 & 1 & \bigm| & 0 \\ 0 & \underline{1} & 1 & \bigm| & 0 \\ 0 & 0 & 0 & \bigm| & \underline{1} \end{bmatrix}$.

Notice that $\tilde{b}$ contains a pivotal 1. So Proposition III tells us that the system has _no_ solutions.

Alternatively, the last row tells us that $0 = 1$, which is a contradiction.

2. Consider the system of equations:

$$
\begin{cases}
2x + y + 3z &= 1 \\
x - y &= 1 \\
x + y + 2z &= 1/3
\end{cases}
$$

then $[A|\vec{b}] = \begin{bmatrix} 2 & 1 & 3 & \bigm| & 1 \\ 1 & -1 & 0 & \bigm| & 1 \\ 1 & 1 & 2 & \bigm| & 1/3 \end{bmatrix}$

which row-reduces to $[\tilde{A}|\tilde{b}] = \begin{bmatrix} \underline{1} & 0 & 1 & \bigm| & 2/3 \\ 0 & \underline{1} & 1 & \bigm| & -1/3 \\ 0 & 0 & 0 & \bigm| & 0 \end{bmatrix}$.

The row-reduced vector $\tilde{b}$ is non-pivotal, so we know there's at least one solution.

Next, notice that the third column is also non-pivotal.

The first row tells us that $x + z = 2/3$; the second, that $y + z = -1/3$. So we can choose some $z$ so that all vectors of the form:

$$
\begin{bmatrix}
2/3 - z \\ -1/3 - z \\ z
\end{bmatrix}
$$

are solutions to the system. In other words, there are _infinitely many_ solutions, as Proposition III would have us believe.

## Proposition IV: Solution to $A\vec{x} = \vec{b}$ via inverses

If $A$ has an inverse $A^{-1}$, then the unique solution to $A\vec{x} = \vec{b}$ is given by $\vec{x} = A^{-1}\vec{b}$.

## Problem 4: Prove Proposition IV.

That is, show that $\vec{x} = A^{-1}\vec{b}$ solves $A\vec{x} = \vec{b}$ and that it is unique.

## Proposition V: Calculating $A^{-1}$ using row reduction

Let $A$ be an $n \times n$ matrix. Construct the $n \times 2n$ augmented matrix $[A|I]$ and put it in row echelon form. Then:

1. If the first $n$ columns row-reduce to the identity, then the last $n$ columns are the inverse of $A$.
2. Otherwise, $A$ is not invertible.

## Example: Computing a matrix inverse

Let $A = \begin{bmatrix} 2 & 1 & 3 \\ 1 & -1 & 1 \\ 1 & 1 & 2 \end{bmatrix}$.

Form the augmented matrix:

$$
[A|I] =
\begin{bmatrix}
2 & 1 & 3 & \bigm| 1 & 0 & 0\\
1 & -1 & 1 & \bigm| 0 & 1 & 0\\
1 & 1 & 2 & \bigm| 0 & 0 & 1
\end{bmatrix}
$$

Row-reducing this matrix gives you:

$$
\begin{bmatrix}
\underline{1} & 0 & 0 & \bigm| & 3 & -1 & -4 \\
0 & \underline{1} & 0 & \bigm| & 1 & -1 & -1 \\
0 & 0 & \underline{1} & \bigm| & -2 & 1 & 3
\end{bmatrix}
$$

and so:

$$
A^{-1} =
\begin{bmatrix}
3 & -1 & -4 \\
1 & -1 & -1 \\
-2 & 1 & 3
\end{bmatrix}
$$


## Example: Showing that $A$ has no inverse

Let $A = \begin{bmatrix} 2 & 1 & 3 \\ 1 & -1 & 0 \\ 1 & 1 & 2 \end{bmatrix}$.

Form the augmented matrix:

$$
[A|I] =
\begin{bmatrix}
2 & 1 & 3 & \bigm| & 1 & 0 & 0\\
1 & -1 & 0 & \bigm| & 0 & 1 & 0\\
1 & 1 & 2 & \bigm| & 0 & 0 & 1
\end{bmatrix}
$$

Row-reducing this matrix gives you:

$$
\begin{bmatrix}
\underline{1} & 0 & 1 & \bigm| & 1 & 0 & -1 \\
0 & \underline{1} & 1 & \bigm| & -1 & 0 & 2 \\
0 & 0 & 0 & \bigm| & -2 & 1 & 3
\end{bmatrix}
$$

Since the row-reduced matrix $\tilde{A}$ on the left is not the identity matrix, $A$ is not invertible.

## Problem 5: Finding inverses

For what values of $a$ and $b$ is the matrix $C = \begin{bmatrix} 1 & -2 & 4 \\ 0 & 5 & -5 \\ 3 & a & b \end{bmatrix}$ invertible?

Calculate the inverse for those values using row reduction.

---

In practice, we don't really solve systems of equations using inverses since they're expensive to calculate. Unless otherwise stated, from this point on you may use `numpy.linalg.inv` to get the inverse of any matrix you find.

## Additional resources

* _The Geometry of Linear Equations_, an MIT OpenCourseWare lecture video by G. Strang: [LINK](https://openlearninglibrary.mit.edu/courses/course-v1:OCW+18.06SC+2T2019/courseware/d2d5b457b440451f82a3453ccc4fc28b/71a4ee751a2d42be8cc603d92f6d8dad/?child=first) (~40 mins)